// This file is generated by a script. Do not modify this file directly, because
// all changes will be lost once the script is run again!
namespace lafe.Logging 
{
	public static partial class LogNumbers
	{
				public const int LoadingLoggingService = 1001;
						
	}
}