// This file is generated by a script. Do not modify this file directly, because
// all changes will be lost once the script is run again!
namespace lafe.ShutdownService.Monitoring 
{
	public static partial class LogNumbers
	{
				public const int InitNetworkPing = 4001;
							public const int ResolvingDnsName = 4002;
							public const int StartingMonitor = 4003;
							public const int StoppingMonitor = 4004;
							public const int TimerEventFired = 4005;
							public const int MonitoringException = 4006;
							public const int PerformingMonitoring = 4007;
							public const int CreateIpCheck = 4008;
							public const int CreateDnsCheck = 4009;
							public const int ComputerStillOnline = 4010;
							public const int NoComputerOnline = 4011;
							public const int ConvertingIp = 4012;
							public const int ConvertedIp = 4013;
							public const int CheckingOnlineState = 4014;
							public const int SendingPing = 4015;
							public const int PingComplete = 4016;
							public const int RoundTripTime = 4017;
							public const int ErrorInOnlineCheck = 4018;
							public const int TimeoutZero = 4019;
							public const int InvalidIpAddress = 4020;
							public const int IpAddressParsingException = 4021;
							public const int NoIpAddress = 4022;
							public const int DnsNameResolved = 4023;
							public const int ResultEmpty = 4024;
							public const int PingResultNull = 4025;
							public const int NoCheckInstancesFound = 4026;
							public const int RunningMonitor = 4027;
							public const int MonitorResult = 4028;
							public const int SkippingMonitors = 4029;
							public const int SystemShuttingDown = 4030;
							public const int RetrievedWin32Object = 4031;
							public const int SecurityPrivilegesEnabled = 4032;
							public const int SetFlagsToShutdown = 4033;
							public const int SendingWin32ShutdownCommand = 4034;
							public const int Bye = 4035;
							public const int ErrorWhilePerformingShutdown = 4036;
							public const int InDebugMode = 4037;
							public const int TryingAlternativeShutdown = 4038;
							public const int ErrorWhilePerformingAlternativeShutdown = 4039;
							public const int DnsResolveException = 4040;
							public const int IpNull = 4041;
							public const int UsingNetworkTimeout = 4042;
						
	}
}