// This file is generated by a script. Do not modify this file directly, because
// all changes will be lost once the script is run again!
namespace lafe.ShutdownService.ServiceLibrary 
{
	public static partial class LogNumbers
	{
				public const int OnContinue = 2001;
							public const int OnPause = 2002;
							public const int OnStart = 2003;
							public const int OnStop = 2004;
							public const int StartingMonitor = 2005;
							public const int StoppingMonitor = 2006;
							public const int RunningInDebugMode = 2007;
						
	}
}