// This file is generated by a script. Do not modify this file directly, because
// all changes will be lost once the script is run again!
namespace lafe.ServiceBase 
{
	public static partial class LogNumbers
	{
				public const int CreatingTimer = 5001;
							public const int StartedTimer = 5002;
							public const int CannotChangeTimerNull = 5003;
							public const int ChangingTimer = 5004;
							public const int ChangedTimer = 5005;
							public const int StoppingTimer = 5006;
							public const int TimerStopped = 5007;
							public const int TimerFired = 5008;
							public const int TimerCallbackComplete = 5009;
							public const int ConsturctorWithPeriod = 5010;
							public const int StartingTimer = 5011;
							public const int PausedTimer = 5012;
							public const int ResumedTimer = 5013;
							public const int TimerCallbackException = 5014;
						
	}
}