//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace lafe.ShutdownService.Configuration {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Configuration {
        
        private TimerConfiguration timerField;
        
        private MonitoredRanges monitoredRangesField;
        
        /// <remarks/>
        public TimerConfiguration Timer {
            get {
                return this.timerField;
            }
            set {
                this.timerField = value;
            }
        }
        
        /// <remarks/>
        public MonitoredRanges MonitoredRanges {
            get {
                return this.monitoredRangesField;
            }
            set {
                this.monitoredRangesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimerConfiguration {
        
        private string checkIntervalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
        public string CheckInterval {
            get {
                return this.checkIntervalField;
            }
            set {
                this.checkIntervalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MonitoredRange {
        
        private RangeType typeField;
        
        private string addressField;
        
        /// <remarks/>
        public RangeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum RangeType {
        
        /// <remarks/>
        Ip,
        
        /// <remarks/>
        Dns,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MonitoredRanges {
        
        private MonitoredRange[] monitoredRangeField;
        
        private string networkTimeoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MonitoredRange")]
        public MonitoredRange[] MonitoredRange {
            get {
                return this.monitoredRangeField;
            }
            set {
                this.monitoredRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string NetworkTimeout {
            get {
                return this.networkTimeoutField;
            }
            set {
                this.networkTimeoutField = value;
            }
        }
    }
}
