// This file is generated by a script. Do not modify this file directly, because
// all changes will be lost once the script is run again!
namespace lafe.ShutdownService.Configuration 
{
	public static partial class LogNumbers
	{
				public const int LoadingConfig = 3001;
							public const int SearchingConfigurationFile = 3002;
							public const int FoundConfiguration = 3003;
							public const int ConfigurationNotFoundAtLocation = 3004;
							public const int LoadingConfigException = 3005;
							public const int UsingConfigurationFile = 3006;
							public const int CreatingXmlReader = 3007;
							public const int CreatingSerializer = 3008;
							public const int CanDeserialize = 3009;
							public const int CannotDeserialize = 3010;
							public const int DeserializingFile = 3011;
							public const int GeneratingPath = 3012;
							public const int ConfigurationLoaded = 3013;
						
	}
}